# Generated by Django 6.0 on 2025-12-29 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achievement_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('click_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ad_identifier', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('target_url', models.TextField()),
                ('source_context', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ad_clicks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('buff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buff_type', models.CharField(choices=[('2x_damage', '2x Damage'), ('2x_attack_speed', '2x Attack Speed'), ('2x_gameplay', '2x Gameplay Speed')], max_length=50)),
                ('multiplier', models.FloatField(default=2.0)),
                ('activated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'buffs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('enemy_id', models.AutoField(primary_key=True, serialize=False)),
                ('enemy_name', models.CharField(max_length=50)),
                ('base_hp', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('speed', models.FloatField()),
                ('reward_gold', models.IntegerField()),
                ('score_reward', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'enemies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.BigIntegerField(default=0)),
                ('level_reached', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'game_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('leaderboard_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('score', models.BigIntegerField()),
                ('level', models.IntegerField(default=1)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leaderboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionStats',
            fields=[
                ('stat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('towers_built', models.IntegerField(default=0)),
                ('towers_upgraded', models.IntegerField(default=0)),
                ('enemies_killed', models.IntegerField(default=0)),
                ('gold_earned', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'session_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('tower_id', models.AutoField(primary_key=True, serialize=False)),
                ('tower_name', models.CharField(max_length=50)),
                ('base_damage', models.IntegerField()),
                ('attack_speed', models.FloatField()),
                ('range', models.FloatField()),
                ('cost', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'towers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TowerUpgrade',
            fields=[
                ('upgrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('upgrade_level', models.IntegerField()),
                ('damage_bonus', models.IntegerField(default=0)),
                ('speed_bonus', models.FloatField(default=0)),
                ('range_bonus', models.FloatField(default=0)),
                ('cost', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tower_upgrades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('wave_id', models.AutoField(primary_key=True, serialize=False)),
                ('wave_number', models.IntegerField()),
            ],
            options={
                'db_table': 'waves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaveEnemy',
            fields=[
                ('wave_enemy_id', models.AutoField(primary_key=True, serialize=False)),
                ('enemy_count', models.IntegerField()),
                ('spawn_interval', models.FloatField()),
            ],
            options={
                'db_table': 'wave_enemies',
                'managed': False,
            },
        ),
    ]
